/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PodcastsRouteImport } from './routes/podcasts'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as EmissionsRouteImport } from './routes/emissions'
import { Route as DedicacesRouteImport } from './routes/dedicaces'
import { Route as ChartRouteImport } from './routes/chart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActusRouteImport } from './routes/actus'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const PodcastsRoute = PodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const EmissionsRoute = EmissionsRouteImport.update({
  id: '/emissions',
  path: '/emissions',
  getParentRoute: () => rootRouteImport,
} as any)
const DedicacesRoute = DedicacesRouteImport.update({
  id: '/dedicaces',
  path: '/dedicaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartRoute = ChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActusRoute = ActusRouteImport.update({
  id: '/actus',
  path: '/actus',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/actus': typeof ActusRoute
  '/auth': typeof AuthRoute
  '/chart': typeof ChartRoute
  '/dedicaces': typeof DedicacesRoute
  '/emissions': typeof EmissionsRoute
  '/newsletter': typeof NewsletterRoute
  '/podcasts': typeof PodcastsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/profile': typeof AuthenticatedProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/actus': typeof ActusRoute
  '/auth': typeof AuthRoute
  '/chart': typeof ChartRoute
  '/dedicaces': typeof DedicacesRoute
  '/emissions': typeof EmissionsRoute
  '/newsletter': typeof NewsletterRoute
  '/podcasts': typeof PodcastsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/profile': typeof AuthenticatedProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/actus': typeof ActusRoute
  '/auth': typeof AuthRoute
  '/chart': typeof ChartRoute
  '/dedicaces': typeof DedicacesRoute
  '/emissions': typeof EmissionsRoute
  '/newsletter': typeof NewsletterRoute
  '/podcasts': typeof PodcastsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/actus'
    | '/auth'
    | '/chart'
    | '/dedicaces'
    | '/emissions'
    | '/newsletter'
    | '/podcasts'
    | '/admin'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/actus'
    | '/auth'
    | '/chart'
    | '/dedicaces'
    | '/emissions'
    | '/newsletter'
    | '/podcasts'
    | '/admin'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/actus'
    | '/auth'
    | '/chart'
    | '/dedicaces'
    | '/emissions'
    | '/newsletter'
    | '/podcasts'
    | '/_authenticated/admin'
    | '/_authenticated/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ActusRoute: typeof ActusRoute
  AuthRoute: typeof AuthRoute
  ChartRoute: typeof ChartRoute
  DedicacesRoute: typeof DedicacesRoute
  EmissionsRoute: typeof EmissionsRoute
  NewsletterRoute: typeof NewsletterRoute
  PodcastsRoute: typeof PodcastsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/podcasts': {
      id: '/podcasts'
      path: '/podcasts'
      fullPath: '/podcasts'
      preLoaderRoute: typeof PodcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emissions': {
      id: '/emissions'
      path: '/emissions'
      fullPath: '/emissions'
      preLoaderRoute: typeof EmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dedicaces': {
      id: '/dedicaces'
      path: '/dedicaces'
      fullPath: '/dedicaces'
      preLoaderRoute: typeof DedicacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart': {
      id: '/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof ChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actus': {
      id: '/actus'
      path: '/actus'
      fullPath: '/actus'
      preLoaderRoute: typeof ActusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ActusRoute: ActusRoute,
  AuthRoute: AuthRoute,
  ChartRoute: ChartRoute,
  DedicacesRoute: DedicacesRoute,
  EmissionsRoute: EmissionsRoute,
  NewsletterRoute: NewsletterRoute,
  PodcastsRoute: PodcastsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
